name: Validate

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: {}

jobs:
  validate-hacs:
    runs-on: "ubuntu-latest"
    steps:
      # Checkout repo
      - uses: actions/checkout@v3
      # Validate Home Assistant integration manifest
      - name: Validate HA manifest
        uses: home-assistant/actions/hassfest@master
      # Validate HACS repository
      - name: HACS validation
        uses: hacs/action@main
        with:
          category: "plugin"

